### ISSUE TITLE
! Issues with version 1.6 of the plugin

### ISSUE THREAD

**Issue by mjmbischoff** [jenkinsci/oic-auth-plugin#62]
As indicated in #46 the spec seems to suggest that the scope shouldn't be send when performing an token request as such we won't be sending the scope anymore and thereby fixing the issue with some openid providers that break on this.

As the inverse could also be true: providers no longer working I've created this issue so people can report issues here.

As the only change between 1.5 and 1.6 is not sending the scope _it is safe to downgrade to 1.5_ and respond to this issue. We will make it configurable in future releases should this be the case.

**Comment by uwehdaub** [comment]
We are using an inhouse developed OpenID connect compliant Auth server.
This is working fine with 1.5 but not with 1.6, because of the missing scope.
I would prefer to have this property configurable in future releases.

**Comment by mjmbischoff** [comment]
@uwehdaub Since the plugin is intended to make life easier for ops people and thus aim for max compatibility within reason - we'll add a configuration parameter in the next version. @uwehdaub

**Comment by talmarco** [comment]
I've tried to integrate OpenID authentication with Jenkins and I'm getting the following error:
_java.lang.Exception: no field 'preferred_username' was supplied in the token payload to be used as the username_
Is this related to one of the changes in this version?

**Comment by caryyu** [comment]
When is version 1.7/1.6.1 going to be published?

**Comment by saikiranp80** [comment]
Hi,
How do I logout from jenkins without logging out from global logout ( global logout forces other pages which uses SSO also to be forced logout).

I enabled “Logout from OpenID Provider” and I am not sure what should be the value for "OpenID Provider logout endpoint URL."

is there a way only to logout properly ( by clearing all sessions & cookies) from jenkins when I use open id plugin so that when I click on login it doesn't login automatically from saved session details.

**Comment by SIkebe** [comment]
I also encountered this issue and reverted it back to 1.5.
>We will make it configurable in future releases should this be the case.

I hope it will be released :-)

**Comment by michael-doubez** [comment]
I'll review the issues as soon as possible. Thanks for the inputs

**Comment by michael-doubez** [comment]
Closing this long issue.

Reading the question, they should be fixed by newer versions.
If not, please, open a new issue.

**Comment by jtnord** [comment]
> We are using an inhouse developed OpenID connect compliant Auth server. This is working fine with 1.5 but not with 1.6, because of the missing scope. I would prefer to have this property configurable in future releases.
> 
> Just stumbled upon this part of the spec: https://tools.ietf.org/html/rfc6749#section-3.3 Seems that the auth server has some freedom, to which the client has to adapt.

However the formative spec is the OIDC spec https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.3.1 which references 4.1.3 which *does not* list the scope.

but in any case per [3.3](https://tools.ietf.org/html/rfc6749#section-3.3) 

the spec allows the client to send the scope - it does not mandate it - and it is only allows to reject the request for the `authorization` endpoint not the `token` endpoint.  thus the in house SP would in my opinion be broken and not spec conforming.

and in [3.2] https://datatracker.ietf.org/doc/html/rfc6749#section-3.2  the parameters must be part of the form
leading to [4.1.3](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3)

If you are not sure I would ask whoever developed your IDP to run the conformant spec checks which can be found [here](https://openid.net/certification/connect_op_testing/) against your server.

Noting this as the library being used is in maintenance mode, and other libraries may not have the flexibility to support non conformant implementations leaving you in limbo.

Same applies to everyone.

can you list the OPs that need the scope sent to the token URL here?  Issues likely need to be filed against them
